In [1]:
import numpy as np

In [4]:
uniform=np.random.rand(3,3)
print("Uniform distribution:\n",uniform)

Uniform distribution:
 [[0.61434205 0.41146464 0.15753821]
 [0.467005   0.73345204 0.48185253]
 [0.34167382 0.93920973 0.35998229]]


# searching in arrays

In [2]:
arr=np.array([1,2,3,4,5])
np.where(arr>3)

(array([3, 4], dtype=int64),)

In [3]:
print("where >3:",np.where(arr>3))

where >3: (array([3, 4], dtype=int64),)


In [7]:
np.where(arr<=2)

(array([0, 1], dtype=int64),)

In [8]:
np.argmax([1,2,3,4,5])

4

In [9]:
np.argmax(arr)

4

In [10]:
np.argmin(arr)

0

In [16]:
#  seraches sorted

sorted_arr=np.array([1,2,3,4,7])
np.searchsorted(sorted_arr,6)

4

In [12]:
np.searchsorted(sorted_arr,100)

5

In [13]:
#  extract
arr=np.array([1,2,3,4,5])
np.extract(arr>3,arr)

array([4, 5])

In [17]:
# transpose
arr=np.array([[1,2,3,4],
             [5,6,7,8]])
np.transpose(arr)

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [18]:
#  mean calculation

arr=np.array([1,2,3,4,5])
print("mean value:",np.mean(arr))

mean value: 3.0


In [ ]:
splitting arrays
np.split()

In [21]:
arr=np.array([1,2,3,4,5,6,7,8])
np.split(arr,4)   # splitting parts equally

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]

In [23]:
# splitting at exact position
arr=np.array([1,2,3,4,5,6])
np.split(arr,[1,4])

[array([1]), array([2, 3, 4]), array([5, 6])]

In [24]:
np.split(arr,[1,3,5])

[array([1]), array([2, 3]), array([4, 5]), array([6])]

In [26]:
# splitting matrix

matrix=np.array([[1,2,3,4],
             [5,6,7,8]])
np.split(matrix ,4,axis=1)

[array([[1],
        [5]]),
 array([[2],
        [6]]),
 array([[3],
        [7]]),
 array([[4],
        [8]])]

In [28]:
matrix=np.array([[1,2,3],
             [4,5,6]])
np.split(matrix ,3,axis=1)     # split columns

[array([[1],
        [4]]),
 array([[2],
        [5]]),
 array([[3],
        [6]])]

In [29]:
# split rows

np.split(matrix ,2,axis=0) 

[array([[1, 2, 3]]), array([[4, 5, 6]])]

In [30]:
# sorting arrays

arr=np.array([1,2,3,4,5,6])
print("sorted array:",np.sort(arr))

sorted array: [1 2 3 4 5 6]


In [32]:
arr.sort()
print("in place sorted:",arr)

in place sorted: [1 2 3 4 5 6]


In [38]:
matrix=np.array([[3,2,1],
             [6,4,5]])
print("sorted rows:\n",np.sort(matrix,axis=1))

sorted rows:
 [[1 2 3]
 [4 5 6]]


In [39]:
print("sorted columns:\n",np.sort(matrix,axis=0))

sorted columns:
 [[3 2 1]
 [6 4 5]]


In [40]:
arr.dtype

dtype('int32')

In [42]:
 # python import numpy as np
 arr = np.array([1, 2, 3], dtype='float')
 print(arr.dtype)

float64
