# numpy

In [13]:
# 1. array module

from array import array
my_array=array('i',[1,2,3,4])      # 'i'  indicates integer data type

In [14]:
my_array

array('i', [1, 2, 3, 4])

In [15]:

import numpy as np
my_array=np.array([1,2,3,4,5,6])


In [16]:
my_array+3

array([4, 5, 6, 7, 8, 9])

In [17]:
type(my_array)

numpy.ndarray

In [18]:
import numpy as np
my_number=np.array([1,2,3,4,5])

In [19]:
import numpy as np
my_numpy_array=np.array([1,2,3,4,5])
new_arr=my_numpy_array*3
new_arr

array([ 3,  6,  9, 12, 15])

In [20]:
type(my_numpy_array)

numpy.ndarray

In [22]:
my_arr=np.array([1,2,3])
res=my_arr*2
res

array([2, 4, 6])

In [23]:
print(res)

[2 4 6]


In [25]:
my_arr

array([1, 2, 3])

In [27]:
my_arr>2

array([False, False,  True])

In [33]:
import seaborn as sns

In [ ]:
df=sns.load_dataset("titanic")


In [41]:
import numpy as np
arr_2d=np.array([[0,1,2,3],[4,5,6,7]])

In [42]:
arr_2d

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [44]:
arr_3d=np.array([[0,1,2,3],[4,5,6,7],[8,9,0,5]])
arr_3d

array([[0, 1, 2, 3],
       [4, 5, 6, 7],
       [8, 9, 0, 5]])

In [46]:
arr_2d+2

array([[2, 3, 4, 5],
       [6, 7, 8, 9]])

In [48]:
arr_2d*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14]])

In [49]:
arr_3d-1

array([[-1,  0,  1,  2],
       [ 3,  4,  5,  6],
       [ 7,  8, -1,  4]])

In [52]:
import pandas as pd
data=pd.read_csv('tit.csv')

In [53]:
print(data.head())

   Unnamed: 0  survived  pclass     sex   age  sibsp  parch     fare embarked  \
0           0         0       3    male  22.0      1      0   7.2500        S   
1           1         1       1  female  38.0      1      0  71.2833        C   
2           2         1       3  female  26.0      0      0   7.9250        S   
3           3         1       1  female  35.0      1      0  53.1000        S   
4           4         0       3    male  35.0      0      0   8.0500        S   

   class    who  adult_male deck  embark_town alive  alone  
0  Third    man        True  NaN  Southampton    no  False  
1  First  woman       False    C    Cherbourg   yes  False  
2  Third  woman       False  NaN  Southampton   yes   True  
3  First  woman       False    C  Southampton   yes  False  
4  Third    man        True  NaN  Southampton    no   True  


In [54]:
data

Unnamed: 0  survived  pclass     sex   age  sibsp  parch     fare  \
0             0         0       3    male  22.0      1      0   7.2500   
1             1         1       1  female  38.0      1      0  71.2833   
2             2         1       3  female  26.0      0      0   7.9250   
3             3         1       1  female  35.0      1      0  53.1000   
4             4         0       3    male  35.0      0      0   8.0500   
..          ...       ...     ...     ...   ...    ...    ...      ...   
886         886         0       2    male  27.0      0      0  13.0000   
887         887         1       1  female  19.0      0      0  30.0000   
888         888         0       3  female   NaN      1      2  23.4500   
889         889         1       1    male  26.0      0      0  30.0000   
890         890         0       3    male  32.0      0      0   7.7500   

    embarked   class    who  adult_male deck  embark_town alive  alone  
0          S   Third    man        True  NaN  Southampton    no  False  
1          C   First  woman       False    C    Cherbourg   yes  False  
2          S   Third  woman       False  NaN  Southampton   yes   True  
3          S   First  woman       False    C  Southampton   yes  False  
4          S   Third    man        True  NaN  Southampton    no   True  
..       ...     ...    ...         ...  ...          ...   ...    ...  
886        S  Second    man        True  NaN  Southampton    no   True  
887        S   First  woman       False    B  Southampton   yes   True  
888        S   Third  woman       False  NaN  Southampton    no  False  
889        C   First    man        True    C    Cherbourg   yes   True  
890        Q   Third    man        True  NaN   Queenstown    no   True  

[891 rows x 16 columns]

In [55]:
list1=[1,2,3,4]
arr_from_list=np.array(list1)
arr_from_list

array([1, 2, 3, 4])