In [2]:
# 2. using functions to geneate data
import numpy as np
a33=np.ones((3,4))
type(a33)

numpy.ndarray

In [3]:
a33

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
a44=np.zeros((2,4))
a44

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
arr1=np.array([1,2,3])

In [9]:
arr1

array([1, 2, 3])

In [11]:
identity_mat=np.eye(3)
identity_mat

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
random_array=np.random.rand(4,4)

In [13]:
random_array

array([[0.07286479, 0.90580295, 0.12602727, 0.12370994],
       [0.19132021, 0.10679692, 0.24100221, 0.40245425],
       [0.2310357 , 0.83021964, 0.87383857, 0.713209  ],
       [0.86830736, 0.50859384, 0.29102109, 0.78014855]])

In [14]:
random_array

array([[0.07286479, 0.90580295, 0.12602727, 0.12370994],
       [0.19132021, 0.10679692, 0.24100221, 0.40245425],
       [0.2310357 , 0.83021964, 0.87383857, 0.713209  ],
       [0.86830736, 0.50859384, 0.29102109, 0.78014855]])

In [15]:
# 3. specific dara type

l=[1,2,3,4]

np.array(l,dtype=np.int32)

array([1, 2, 3, 4])

In [19]:
float_array=np.array([1,2,3], dtype=np.float64)
int_array=np.array([1,2,3,4], dtype=np.int32)

In [20]:
float_array

array([1., 2., 3.])

In [21]:
int_array

array([1, 2, 3, 4])

In [22]:
# 4. using array and linespace
# arange()

a44=np.arange(0,12)
a44

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [24]:
a66=np.arange(5,7)
a66

array([5, 6])

In [31]:
#  linespace

linespace_array=np.linspace(0,10,6)
linespace_array

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [33]:
linespace_array=np.linspace(1,20,5)
linespace_array

array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ])

In [34]:
random_array=np.random.rand(4,4)  # CREATES random values in(0,1)
random_array

array([[0.30268031, 0.20299391, 0.53642627, 0.28364427],
       [0.91811194, 0.28344408, 0.13402096, 0.29033888],
       [0.76178578, 0.09879835, 0.96277772, 0.84888214],
       [0.96775923, 0.47701543, 0.35165312, 0.31379971]])

# Numpy array Indexing

In [35]:
# 1. basic indexing

arr=np.array([10,20,30,40])
print(arr[0])

10


In [36]:
arr[-1]

40

In [37]:
# 2d example
matrix=np.array([[1,2,3],
                 [4,5,6]])
matrix[0,1]

2

In [38]:
print(matrix[1,2])

6


In [39]:
# 2. slicing
# 1d array slicing

arr=np.array([10,20,30,40,50,60])
print(arr[0:4])

[10 20 30 40]


In [40]:
print(arr[1:])

[20 30 40 50 60]


In [41]:
print(arr[:-1])

[10 20 30 40 50]


In [42]:
print(arr[::-1])

[60 50 40 30 20 10]


In [45]:
print(arr[::2])

[10 30 50]


In [47]:
print(arr[0:4:3])

[10 40]


In [48]:
print(arr[:3])

[10 20 30]


In [66]:
# 2d array slicing

matrix=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

matrix[0:2,1:3]

array([[2, 3],
       [5, 6]])

In [67]:
print(matrix[1:3,1:3])

[[5 6]
 [8 9]]


In [68]:
# 8
print(matrix[2:3,1:2])

[[8]]


In [69]:
print(matrix[2:,1:])

[[8 9]]


In [70]:
matrix[2:3,1:2]

array([[8]])

In [71]:
#  numpy array copy vs view

#  view

a=np.array([1,2,3,4])
b=a[1:3]  # view
b

array([2, 3])

In [72]:
b[0]=99
print(a)

[ 1 99  3  4]


In [76]:
a=[1,2,3,4]
b=a
b

[1, 2, 3, 4]

In [77]:
b[2]=99
b

[1, 2, 99, 4]

In [78]:
a

[1, 2, 99, 4]

In [75]:
# copy
a=np.array([1,2,3,4])
b=a[1:3].copy()  # view
b[0]=99
print(a)
print(b)

[1 2 3 4]
[99  3]


In [80]:
#  numpy shape and reshaping
#  shape
arr=np.array([[1,2,3],[4,5,6]])
print(arr.shape)



(2, 3)


In [ ]:
arr=np.array([0,1,2,3,4,5,6,7,8,9,10,11])

In [81]:
a=np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [82]:
# reshape
b=a.reshape(3,4)   # to change the shape without changing the data
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [83]:
#  numpy array attributes
# transpose

matrix=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

matrix.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [84]:
arr=np.array([[1,2,3,4,5,6],
             [10,20,30,40,50,60]])
arr.transpose()

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30],
       [ 4, 40],
       [ 5, 50],
       [ 6, 60]])

In [85]:
arr3d=np.array([[0,1,2,3],
               [4,5,6,7],
               [8,9,10,11]])
arr3d.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])